# Generated by Django 5.2 on 2025-04-08 18:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoredURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name or identifier', max_length=255)),
                ('url', models.URLField(help_text='URL to monitor for price changes', max_length=2000)),
                ('marketplace', models.CharField(choices=[('amazon', 'Amazon'), ('ebay', 'eBay'), ('walmart', 'Walmart'), ('etsy', 'Etsy'), ('shopify', 'Shopify'), ('target', 'Target'), ('best_buy', 'Best Buy'), ('newegg', 'Newegg'), ('other', 'Other')], default='amazon', max_length=50)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('previous_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('monitoring_frequency', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=20)),
                ('alert_threshold_percentage', models.DecimalField(decimal_places=2, default=5.0, help_text='Percentage change that triggers an alert', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitored_urls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percentage_change', models.DecimalField(decimal_places=2, max_digits=7)),
                ('is_increase', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to='price_monitor.monitoredurl')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='price_monitor.monitoredurl')),
            ],
            options={
                'verbose_name_plural': 'Price histories',
                'ordering': ['-timestamp'],
            },
        ),
    ]
