apiVersion: apps/v1
kind: Deployment
metadata:
  name: repricing-platform-web
  namespace: repricing-platform
  labels:
    app: repricing-platform
    component: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: repricing-platform
      component: web
  template:
    metadata:
      labels:
        app: repricing-platform
        component: web
    spec:
      containers:
      - name: web
        image: repricing-platform:latest
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "repricing_platform.settings.prod"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DATABASE_URL
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: REDIS_URL
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: SECRET_KEY
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: STRIPE_SECRET_KEY
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health/live/
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health/ready/
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: repricing-platform-worker
  namespace: repricing-platform
  labels:
    app: repricing-platform
    component: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: repricing-platform
      component: worker
  template:
    metadata:
      labels:
        app: repricing-platform
        component: worker
    spec:
      containers:
      - name: worker
        image: repricing-platform:latest
        command: ["celery", "-A", "repricing_platform", "worker", "--loglevel=info", "--concurrency=4"]
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "repricing_platform.settings.prod"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DATABASE_URL
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: REDIS_URL
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: SECRET_KEY
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: repricing-platform-beat
  namespace: repricing-platform
  labels:
    app: repricing-platform
    component: beat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: repricing-platform
      component: beat
  template:
    metadata:
      labels:
        app: repricing-platform
        component: beat
    spec:
      containers:
      - name: beat
        image: repricing-platform:latest
        command: ["celery", "-A", "repricing_platform", "beat", "--loglevel=info", "--scheduler", "django_celery_beat.schedulers:DatabaseScheduler"]
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "repricing_platform.settings.prod"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DATABASE_URL
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: REDIS_URL
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: SECRET_KEY
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"
